# Generated by Django 5.2.6 on 2025-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
