# Generated by Django 5.2.6 on 2025-09-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
